### ISSUE TITLE
Maximum input sample size

### ISSUE THREAD

**Issue by Bai-Jiang** [PythonOT/POT#102]
I have two data samples, each of size 100k, from two distributions in the 50-dimensional space, say n = 100k, p = 50. Can I use this OT library to compute the earth-mover distance between these two empirical data samples?

**Comment by ngayraud** [comment]
If I understand correctly, I don't see why not. It might take a while
though so be careful to tune the regularization parameter ( if you use
sinkhorn ) and consider normalizing the cost matrix.

**Comment by rflamary** [comment]
Hello,

If you want to compute the true EMD it could also work but you will need a large memory so that you can store the cost matrix M (10^5x10^5). You will also need memory to store the solution G in non-sparse format. We are working on providing a solver returning sparse format but it is not ready (nor in the PR) right now.
