### ISSUE TITLE
Parameter `dense` for emd2

### ISSUE THREAD

**Issue by mglisse** [PythonOT/POT#166]
https://github.com/PythonOT/POT/blob/0a1e8cd6d63b354fe7dfe0439c08417ecf988121/ot/lp/__init__.py#L330

Hello,

the documentation gave me some hope that I could pass `dense=False` to `emd2`, but apparently this argument does not actually exist :disappointed: 
Could you either remove it from the doc, or even better actually implement it?
(looks like this bit was missed in #158)

**Comment by rflamary** [comment]
Yes we will remove it from the documentation.

We had implemented emd so that it returns sparse matrices but due to numerical problems in the C++ solver it was not stable and would not be implemented. Since the cost needs to be dense in memory for the solver the sparse output needed to be computed a posteriori which can be done outside of the solver.

**Comment by mglisse** [comment]
Ah, ok. I was going to use it in cases where all the weights are (small) integers, where I expect numerical problems are less likely, but I can understand that the general case may be harder. And yes, we already compute the sparse output a posteriori.
Thanks for the explanation.
