### ISSUE TITLE
Inverse transform for MappingTransport

### ISSUE THREAD

**Issue by obernardoff** [PythonOT/POT#193]
## 🚀 Feature
We are implenting a grid search function for fitting the best parameters for each transport function. For the circular validation, we need to inverse the transformation. It works well on all algorithms based on _BaseTransport._ However, as _MappingTransport_ is based on _BaseEstimator_ we do not have access to the inverse transform function. 

## ❔ Questions 
Is it possible to apply the _inverse_transform_ function  from the _BaseTransport_ to the _MappingTransport_ ? If no, how can we deal with this issue ?

👏 We would like to thank you for the quality of POT code and documentation.
Kind regards,
@obernardoff @nkarasiak @YousraH @dsheeren

**Comment by rflamary** [comment]
Hello,

I'm very interested by a clean circular validation implementation, I encourage you to submit it to POT when you are done.

MappingTransport does estimate a mapping but only in one dimension, it means that for the other direction you need to fit it with reversed Xs/Xt. I know it's a pain but the method was designed only for training in one direction.

In any case you have to be careful about invese tranform because it uses the OT matrix estimated on the source/target given during fit. If you do circular validation maybe you need to fit thao class again after the samples are transported (unless you have the same number of point and in this case its OK because barycentric mapping is exact).

**Comment by nkarasiak** [comment]
Thank you for the quick reply @rflamary.

Indeed we noticed that inverse transform was not suitable when we had two different number of points for Xs and Xt, so we'll do a new fit indeed ! 

We implement a gridsearch approach to automatically find the parameters of the algorithm. By now we use the root mean square error, but we will set a default metric and the user will have the possibility to choose its own metric. If you have any suggestion let us know !

**Comment by rflamary** [comment]
one nice metric for DA is to see if you can preserve labels during the circular mapping. For instance you can use the new transform_labels function implemented by @ievred  : https://github.com/PythonOT/POT/blob/master/ot/da.py#L1083
to transport labels in one direction than do an argmax to select a unique label for each transported labels on target samples and do that again to see if the labels are preserved.

This last function is a way to label existing target samples using the OT matrix (barycentric label mapping in fact).
