### ISSUE TITLE
sinkhorn_knopp_unbalanced returns only the first term of the loss function.

### ISSUE THREAD

**Issue by emmanuel-hartman** [PythonOT/POT#245]
It seems that when using sinkhorn_knopp_unbalanced for batch computation the losses that are returned only include the one term of the unbalanced OT loss function. Currently, the function simply returns 

<\gamma,M>_F 

and does not add the additional terms

reg\cdot\Omega(\gamma) + reg_m KL(\gamma 1, a) + reg_m KL(\gamma^T 1, b).

**Comment by rflamary** [comment]
Hello,

sinkhorn_knopp_unbalanced actually return the optimal plan \Omega, you can compute the linear part of the loss or the complete loss from this.

**Comment by emmanuel-hartman** [comment]
In the case where n_hists!=0 (i.e. when it has been called for batch computation or from sinkhorn_unbalanced2), the function returns a single float which gives only the first term of the loss.

**Comment by rflamary** [comment]
Yes that's true, it is the default case because we did not want to return several full OT matrices in memory and the linear term is often the one that is used (for instance in the original paper from Cuturi).

You can get the dual variable from the log with log=True and compute it afterwards. It is not very practical but it is a quick hack. Note that we are working on a new API that will allow you to get the linear or full loss more efficiently but it's going to take some time.
