### ISSUE TITLE
Few questions about the implementation of "stabilized_sinkhorn"

### ISSUE THREAD

**Issue by vineelpratap** [PythonOT/POT#248]
1. https://github.com/PythonOT/POT/blob/d06eee87155cdc6702c0dc8fe933dc02d9efdada/ot/bregman.py#L748-L751 

I think this block should be unindented .

2. https://github.com/PythonOT/POT/blob/d06eee87155cdc6702c0dc8fe933dc02d9efdada/ot/bregman.py#L745 

Just curious, if there is a reason for using `np.max` here. The algorithm proposed in https://arxiv.org/pdf/1610.06519.pdf  (Algo 2) doesn't seem to take the `max`.

**Comment by rflamary** [comment]
I agree with your first comment.

To answer your second, we have a shared Cost matrix C and in order to keep an efficient computation we need to perform a joint stabilization. In order to avoid numerical experiments we take the largest value among all the tasks. Note that this was not discussed in the paper so we chose to take the maximum instead of having as many stabilized K matrices as tasks.

**Comment by vineelpratap** [comment]
Hi,
  Thanks for the response ! I have one follow up question regarding my second question.  I was wondering why do we take `np.max` only one `n_hists != 0` ?

**Comment by rflamary** [comment]
because you do not need to take the max if you have only one histogram (we take the max in dimension 1 that is across histograms)
