### ISSUE TITLE
Looking for ideas on FGW usage

### ISSUE THREAD

**Issue by dawe** [PythonOT/POT#270]
Hi all, I have two datasets that include different types of features on entries that are partly shared. I build graphs out these features to perform many kind of analysis and now I'm interested in OT. In particular I'm trying to use FGW to test how it performs on my problems.
I have some doubts about what would be the appropriate cost matrix across domains. In fact, if I build the graphs using the same node order and I define M as the distance between the two laplacians (whereas cost matrix for source and target are the shortest paths), I have perfect results in identifying corresponding nodes.
If I build the graphs with the same nodes but not in the same order, the trick doesn't work. 
The problem extends to the case where I use all entries from both datasets, so that the size of both graphs is different.  In that case any metric in `ot.dist` to define M will fail as matrices (either shortest paths or any other vertex property) will have different ranks.
I was reading the FGW paper, which states that "when dealing with real valued vector attributed graphs, we consider the l2 distance between the labels of the vertices", but again, as my graphs are unlabeled, what would it be an appropriate measure for labels?

**Comment by tvayer** [comment]
Hello dawe, it is a good question but I am afraid that there is no definitive answer. First if your graphs are unlabeled maybe you can check if a "simple" Gromov-Wasserstein distance would be sufficient for your task. Otherwise I believe it highly depends on your data and the L2 distance is just a simple choice. I am not really sure to understand what kind of graphs you have based on your comment and what do you mean by " distance between the two laplacians": is it the froebenius distance between the two matrices ? In this case indeed if the matrices do not share the same dimension it would not work.

The idea is that the C matrices should encode the "structural properties" of the graphs (eg shortest path between the nodes or laplacian) and the M matrix the distance between the "features informations" of the nodes of the 2 graphs.  When you do not have any natural feature maybe one possibility is to consider something like the "centrality" of the nodes (https://en.wikipedia.org/wiki/Centrality). It would give you a 1D feature per node that can be used to construct M, maybe it helps for your task.

**Comment by dawe** [comment]
Hello @tvayer. Thanks for answering here (in addition to the gitter room).
Some groups are working in this field (biology) and they actually use the GW distance across modalities (see [here](https://www.biorxiv.org/content/10.1101/2020.04.28.066787v2.abstract) or [here](https://www.biorxiv.org/content/10.1101/2021.03.19.436159v1.full)), but as soon as I moved my steps into OT I thought FGW could be a more powerful solution.
The distance between laplacian was calculated with `ot.dist()`, so `sqeuclidean` was in place (as default). That worked (by chance) because I had graphs with the same node order.
I already tried to use node properties (mostly centrality measures) but it didn't work as hoped. 
I have natural features for all nodes, but as they are from different modalities I cannot calculate distances across them directly. One solution may be to project data into some appropriate embedding. I'll perform some more tests.
Thanks!

**Comment by tvayer** [comment]
Okay I see.. From experience, the hyparameter alpha is a bit sensitive too, sometimes you have to look for very small or very high (close to 1) value in order to find one that suits your problem.. If you have features but from different spaces maybe one remedy also could be to use GW with intra cost matrices as (for each graph):

C = (1-alpha)* C_1 + alpha * C_2

where C_1 is shortest-path and C_2 is the pair-to-pair distances between the features inside each graph.

Hope it helps.
