### ISSUE TITLE
pymanopt.function import error

### ISSUE THREAD

**Issue by AndresMorales-USC** [PythonOT/POT#370]
## Bug Description
When trying to import Wasserstein Discriminant Analysis, I was getting an import error with pymanopt.

```
<ipython-input-1-59e825483443> in <module>
----> 1 from ot.dr import wda

~\anaconda3\envs\DeepSeg_py36_np117_env\lib\site-packages\ot\dr.py in <module>
     18 from scipy import linalg
     19 import autograd.numpy as np
---> 20 from pymanopt.function import Autograd
     21 from pymanopt.manifolds import Stiefel
     22 from pymanopt import Problem

ImportError: cannot import name 'Autograd'
```

This error is due to the pymanopt package [Jan 8, 2022 commit d2ae53df7ddac0c7b64b83ae414105c0d3ba3033] converting function decorator names to lowercase. (the earlier version of pymanopt on pypi [0.5.2] doesn't even have function.py from which to call Autograd)
I'm unsure of what changes would be necessary for POT to match either the dev version of pymanopt on github (other than changing backend names to lower-case) or the version on pypi.
What was the last stable commit of pymanopt that works as POT expects it to?

### Environment:
Windows-10-10.0.19041-SP0
Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]
NumPy 1.19.5
SciPy 1.3.0
POT 0.8.2
PyManOpt dev

**Comment by rflamary** [comment]
OK so if pymanopt change their API in new version we will need to do the same indeed.

For the moment POT works on the pipy released pymanopt : 
https://github.com/PythonOT/POT/runs/6113969779?check_suite_focus=true

You can see that ll wda tests pass (on linux at least) .

The best thing would be to do a try catch so that the code works for both. Do you want to propose a PR?

In the end it would probably be better to implement a backend of WDA loss to that people can directly use pymanopt with the backhend of their choice... Feel free to also add it if you want to contribute.

**Comment by AndresMorales-USC** [comment]
OHHH! Sorry for my confusion. I thought POT required the latest stable release of PyManOpt on pypi [version 0.2.5] (which doesn't have function.py from which to import the Autograd backend and throws an error), when in fact it requires the latest release [version 0.2.6rc1].
