### ISSUE TITLE
An Issue regarding "line_search_armijo" function in a GPU Environment

### ISSUE THREAD

**Issue by Nuwaisir-1998** [PythonOT/POT#445]
I'm using `gcg` method of `optim.py` in a GPU environment which calls `line_search_armijo` function. There is a call to the method `scalar_search_armijo` of `scipy.optimize` (at `_linesearch.py`) inside the `line_search_armijo` function. In this `scalar_search_armijo` method if the while loop starting with `while alpha1 > amin:` is executed, `alpha2 = (-b + np.sqrt(abs(b**2 - 3 * a * derphi0))) / (3.0*a)` - this statement causes an error as `np` is used with cuda variables. Importantly, `a`, and `b` are in cuda device because it is calculated using `phi` which is passed from and defined in `line_search_armijo` function and returns a value residing in cuda device. A simple change (removing the np dependency and taking `alpha2` into cpu) inside the `scalar_search_armijo` method of `scipy.optimize` solves the issue, but I don't think that is a good idea to change scipy's code. Can you suggest a better solution to this?

**Comment by rflamary** [comment]
This is a good point those function need to work for cuda arrays

I think the best way to work with the scipy implementation is to add `nx.to_numpy()` to the following line:
https://github.com/PythonOT/POT/blob/a5930d3b3a446bf860d6dfacc1e17151fae1dd1d/ot/optim.py#L83

Since we are talking about a small aray/value the overhead will be quite small compare to the call to f

Do you wnat to propose a PR @Nuwaisir-1998 ? @cedricvincentcuaz you juste worked on the code you might be able to do that more quicly?

**Comment by cedricvincentcuaz** [comment]
Thank you again @Nuwaisir-1998 , i am on it.

**Comment by rflamary** [comment]
the last PR from @cedricvincentcuaz should have fixed the problem, i'm closing the issue
