### ISSUE TITLE
Gromov-Wasserstein, standardizing conventions

### ISSUE THREAD

**Issue by patrick-nicodemus** [PythonOT/POT#461]
In Facundo Memoli's original paper on the Gromov-Wasserstein distance, in the Foundations for Computational Mathematics journal (2011), _Gromov_Wasserstein distances and the metric approach to object matching,_ he defines the Gromov-Wasserstein distance on page 450 as follows.
![image](https://user-images.githubusercontent.com/32827763/232587303-a80d591c-eaee-489f-a550-c7c4c15cd6e8.png)
According to your documentation, you are not including the multiplicative factor of 1/2 and the power of 1/p in this picture. Of course, they are equivalent problems to solve, it is trivial to convert a solution to one problem into the other, but without the power of 1/p, this probably is not a metric. It is somewhat annoying to have two different definitions of the GW distance floating around depending on whether we are counting the 1/2 and the 1/p and whether we care about the metric axioms. Would you mind changing the user interface so that the returned GW distance agrees with the one in the paper?

**Comment by rflamary** [comment]
Hello, I agree that we are not computing the GW distance and maybe we should be more clear in the documentation but we have several reasons for our solver to return GW^p. 

The solver is much more geenral that juste computing GW distance because you can give it any pairwise relationship matrice (even no symmetric) and can also handle KL instead of quadratic loss when the power p makes no sens. In most application people are also often interested in GW^p (GW barycenters for instance).  

The name of the function is probably not the best but POT is already used by many people and we cannot change what is returned by the function with API breaking changes. But I welcome a PR if you want to make the documentaion more rigourous (for instance with a sentence discussion how to compute the actual GW distance from Memoli, and changing GW as GW_loss)
